// AI Coding Tools Spectrum - data (April 2026)
//
// X axis (all charts): REALISTIC monthly cost in USD. Free tiers burn out,
// we plot what you actually pay to use the tool seriously.
//
// Y axis (per category):
//   chat  → context window size in thousands of tokens (log)
//   ide   → autonomy level 1..4 (1=autocomplete, 2=chat+edit, 3=multi-file agent, 4=plan+execute)
//   cli   → scope 1..4 (1=pair programmer, 2=tool-use agent, 3=multi-step planner, 4=swarm/multi-agent)
//   infra → breadth = number of models supported (log)

export type Category = "chat" | "ide" | "cli" | "infra";

export type Tool = {
  id: string;
  name: string;
  category: Category;
  /** realistic monthly cost in USD to actually use the tool */
  price: number;
  /** ceiling of the highest sane consumer tier */
  priceMax?: number;
  /**
   * Per-category Y value:
   *   chat  → context window in thousands (e.g. 200 = 200K tokens)
   *   ide   → 1..4 autonomy
   *   cli   → 1..4 scope
   *   infra → number of models supported
   */
  y: number;
  /** legacy capability tier for overview chart (1..5) */
  overviewTier: number;
  oss: boolean;
  freeKind: "yes" | "trial" | "byok" | "none";
  freeNote?: string;
  blurb: string;
  url: string;
};

export const TOOLS: Tool[] = [
  // ───── CHAT (y = context window in K tokens) ─────
  {
    id: "deepseek",
    name: "DeepSeek",
    category: "chat",
    price: 1,
    y: 128,
    overviewTier: 1,
    oss: true,
    freeKind: "yes",
    freeNote: "Web chat unlimited",
    blurb: "Cheapest frontier reasoning. Open weights.",
    url: "https://chat.deepseek.com",
  },
  {
    id: "qwen",
    name: "Qwen",
    category: "chat",
    price: 1,
    y: 256,
    overviewTier: 1,
    oss: true,
    freeKind: "yes",
    freeNote: "Free app",
    blurb: "Alibaba. Strong coding, multilingual.",
    url: "https://qwen.ai",
  },
  {
    id: "zai",
    name: "Z.ai (GLM-5)",
    category: "chat",
    price: 9,
    priceMax: 72,
    y: 200,
    overviewTier: 1,
    oss: true,
    freeKind: "yes",
    freeNote: "Free chat",
    blurb: "Zhipu. Lite $9/mo · Pro $27/mo · Max $72/mo (quarterly).",
    url: "https://chat.z.ai",
  },
  {
    id: "minimax",
    name: "MiniMax M2.7",
    category: "chat",
    price: 10,
    priceMax: 150,
    y: 1000,
    overviewTier: 1,
    oss: true,
    freeKind: "yes",
    freeNote: "Free chat + pay-as-you-go",
    blurb: "Starter $10 → Ultra-Highspeed $150. 1M context.",
    url: "https://chat.minimax.io",
  },
  {
    id: "kimi",
    name: "Kimi K2.5",
    category: "chat",
    price: 15,
    priceMax: 159,
    y: 256,
    overviewTier: 1,
    oss: true,
    freeKind: "yes",
    freeNote: "Free web/app",
    blurb: "Moonshot. Moderato $15 → Vivace $159. 256K context.",
    url: "https://kimi.moonshot.cn",
  },
  {
    id: "mistral",
    name: "Mistral Le Chat",
    category: "chat",
    price: 14.99,
    priceMax: 24.99,
    y: 128,
    overviewTier: 1,
    oss: false,
    freeKind: "yes",
    freeNote: "Free tier available",
    blurb: "EU-hosted. Pro $14.99 · Team $24.99. Student $5.99.",
    url: "https://chat.mistral.ai",
  },
  {
    id: "gemini",
    name: "Gemini",
    category: "chat",
    price: 19.99,
    priceMax: 249.99,
    y: 1000,
    overviewTier: 1,
    oss: false,
    freeKind: "trial",
    freeNote: "Limited 3.x in app",
    blurb: "Plus $7.99 · Pro $19.99 · Ultra $249.99. 1M ctx.",
    url: "https://gemini.google.com",
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    category: "chat",
    price: 20,
    priceMax: 200,
    y: 256,
    overviewTier: 1,
    oss: false,
    freeKind: "trial",
    freeNote: "10 msgs / 5h",
    blurb: "Go $8 · Plus $20 · Pro $200.",
    url: "https://chatgpt.com",
  },
  {
    id: "claude",
    name: "Claude.ai",
    category: "chat",
    price: 20,
    priceMax: 200,
    y: 200,
    overviewTier: 1,
    oss: false,
    freeKind: "trial",
    freeNote: "Limited Sonnet",
    blurb: "Pro $20 · Max $100 / $200. 200K ctx (1M Max).",
    url: "https://claude.ai",
  },
  {
    id: "grok",
    name: "Grok",
    category: "chat",
    price: 30,
    priceMax: 300,
    y: 256,
    overviewTier: 1,
    oss: false,
    freeKind: "trial",
    freeNote: "10 prompts / 2h",
    blurb: "xAI. Lite $10 · Standard $30 · Heavy $300.",
    url: "https://grok.com",
  },

  // ───── IDE (y = 1..4 autonomy) ─────
  {
    id: "continue",
    name: "Continue",
    category: "ide",
    price: 3,
    priceMax: 20,
    y: 2,
    overviewTier: 2,
    oss: true,
    freeKind: "byok",
    freeNote: "$3/M tokens usage-based",
    blurb: "Starter $3/M tokens · Team $20/seat.",
    url: "https://continue.dev",
  },
  {
    id: "cline",
    name: "Cline",
    category: "ide",
    price: 1,
    y: 3,
    overviewTier: 3,
    oss: true,
    freeKind: "yes",
    freeNote: "100% OSS. BYOK free providers.",
    blurb: "Plan/Act agent in VS Code. Token-hungry, use free providers.",
    url: "https://cline.bot",
  },
  {
    id: "roo-code",
    name: "Roo Code",
    category: "ide",
    price: 15,
    priceMax: 99,
    y: 3,
    overviewTier: 3,
    oss: true,
    freeKind: "yes",
    freeNote: "Free extension + Cloud Free tier",
    blurb: "Extension free (BYOK) · Cloud Team $99/mo.",
    url: "https://roocode.com",
  },
  {
    id: "kilo-code",
    name: "Kilo Code",
    category: "ide",
    price: 1,
    y: 3,
    overviewTier: 3,
    oss: true,
    freeKind: "yes",
    freeNote: "100% OSS. BYOK free providers.",
    blurb: "Superset of Cline + Roo. Many modes. Works with free providers.",
    url: "https://kilocode.ai",
  },
  {
    id: "zed",
    name: "Zed",
    category: "ide",
    price: 10,
    y: 3,
    overviewTier: 3,
    oss: true,
    freeKind: "byok",
    freeNote: "Free w/ BYO key",
    blurb: "Native Rust editor. Zed Pro $10 (+usage).",
    url: "https://zed.dev",
  },
  {
    id: "copilot-student",
    name: "Copilot (Student)",
    category: "ide",
    price: 1,
    y: 3,
    overviewTier: 3,
    oss: false,
    freeKind: "yes",
    freeNote: "Free w/ GitHub Student Pack",
    blurb: "The single best free deal in the market.",
    url: "https://education.github.com/pack",
  },
  {
    id: "copilot",
    name: "GitHub Copilot",
    category: "ide",
    price: 10,
    priceMax: 39,
    y: 3,
    overviewTier: 3,
    oss: false,
    freeKind: "yes",
    freeNote: "50 requests/mo free",
    blurb: "Free · Pro $10 · Pro+ $39.",
    url: "https://github.com/features/copilot",
  },
  {
    id: "windsurf",
    name: "Windsurf",
    category: "ide",
    price: 20,
    priceMax: 200,
    y: 3,
    overviewTier: 3,
    oss: false,
    freeKind: "trial",
    freeNote: "Free tier exists",
    blurb: "Codeium. Pro $20 · Max $200.",
    url: "https://windsurf.com",
  },
  {
    id: "trae",
    name: "Trae",
    category: "ide",
    price: 3,
    priceMax: 100,
    y: 3,
    overviewTier: 3,
    oss: false,
    freeKind: "trial",
    freeNote: "Free tier with limits",
    blurb: "ByteDance IDE. Pro $3 · Pro+ $30 · Ultra $100.",
    url: "https://trae.ai",
  },
  {
    id: "cursor",
    name: "Cursor",
    category: "ide",
    price: 20,
    priceMax: 200,
    y: 3,
    overviewTier: 3,
    oss: false,
    freeKind: "trial",
    freeNote: "Hobby (burns fast)",
    blurb: "Pro $20 · Pro+ $60 · Ultra $200.",
    url: "https://cursor.com",
  },
  {
    id: "amp",
    name: "Amp",
    category: "ide",
    price: 5,
    y: 4,
    overviewTier: 3,
    oss: false,
    freeKind: "byok",
    freeNote: "No sub. Min $5 credit, pass-through API pricing.",
    blurb: "Sourcegraph. Zero markup on provider API costs.",
    url: "https://ampcode.com",
  },
  {
    id: "antigravity",
    name: "Antigravity",
    category: "ide",
    price: 20,
    y: 4,
    overviewTier: 3,
    oss: false,
    freeKind: "trial",
    freeNote: "Preview access",
    blurb: "Google's agentic IDE. Multi-agent planning.",
    url: "https://antigravity.google",
  },
  {
    id: "replit",
    name: "Replit Core",
    category: "ide",
    price: 25,
    priceMax: 40,
    y: 4,
    overviewTier: 3,
    oss: false,
    freeKind: "trial",
    freeNote: "Starter credit",
    blurb: "Cloud IDE + AI agent. Core $25 · Pro $40.",
    url: "https://replit.com",
  },
  {
    id: "predev",
    name: "pre.dev",
    category: "ide",
    price: 30,
    y: 4,
    overviewTier: 3,
    oss: false,
    freeKind: "trial",
    freeNote: "Limited preview",
    blurb: "Autonomous product builder from specs.",
    url: "https://pre.dev",
  },

  // ───── CLI (y = 1..4 scope) ─────
  {
    id: "aider",
    name: "Aider",
    category: "cli",
    price: 1,
    y: 1,
    overviewTier: 4,
    oss: true,
    freeKind: "yes",
    freeNote: "100% OSS. BYOK free providers.",
    blurb: "Git-aware pair programmer. Works with free providers.",
    url: "https://aider.chat",
  },
  {
    id: "gemini-cli",
    name: "Gemini CLI",
    category: "cli",
    price: 1,
    y: 2,
    overviewTier: 4,
    oss: true,
    freeKind: "yes",
    freeNote: "1,000 req/day free, indefinitely",
    blurb: "Best genuinely-free terminal agent.",
    url: "https://github.com/google-gemini/gemini-cli",
  },
  {
    id: "codex-cli",
    name: "Codex CLI",
    category: "cli",
    price: 8,
    priceMax: 200,
    y: 3,
    overviewTier: 4,
    oss: true,
    freeKind: "yes",
    freeNote: "Free w/ ChatGPT Free + Go",
    blurb: "GPT-5 Codex agent. Bundled w/ ChatGPT Go $8 → Pro $200.",
    url: "https://developers.openai.com/codex/cli",
  },
  {
    id: "opencode",
    name: "opencode",
    category: "cli",
    price: 1,
    y: 3,
    overviewTier: 4,
    oss: true,
    freeKind: "yes",
    freeNote: "100% OSS. BYOK free providers.",
    blurb: "Provider-agnostic coding agent. Works with free providers.",
    url: "https://opencode.ai",
  },
  {
    id: "crush",
    name: "Crush",
    category: "cli",
    price: 1,
    y: 3,
    overviewTier: 4,
    oss: true,
    freeKind: "yes",
    freeNote: "100% OSS, works with free providers",
    blurb: "Charm. Glamorous TUI. 22.7k ★. BYOK: Groq free / OpenRouter free / Z.ai / etc.",
    url: "https://github.com/charmbracelet/crush",
  },
  {
    id: "goose",
    name: "Goose",
    category: "cli",
    price: 1,
    y: 3,
    overviewTier: 4,
    oss: true,
    freeKind: "yes",
    freeNote: "100% OSS. BYOK free providers.",
    blurb: "Block. MCP-first extensible agent. Works with free providers.",
    url: "https://block.github.io/goose",
  },
  {
    id: "claude-code",
    name: "Claude Code",
    category: "cli",
    price: 20,
    priceMax: 200,
    y: 4,
    overviewTier: 5,
    oss: false,
    freeKind: "none",
    blurb: "Bundled w/ Claude Pro $20 · Max $100/$200.",
    url: "https://claude.com/claude-code",
  },

  // ───── INFRA (y = number of models, log) ─────
  // Providers: hosted own infra, finite catalog
  {
    id: "groq",
    name: "Groq",
    category: "infra",
    price: 1,
    y: 14,
    overviewTier: 5,
    oss: false,
    freeKind: "yes",
    freeNote: "Free tier + pay-per-token",
    blurb: "LPU. Fastest Llama/Kimi/Qwen (1000+ TPS). 14 models.",
    url: "https://groq.com",
  },
  {
    id: "deepinfra",
    name: "DeepInfra",
    category: "infra",
    price: 1,
    y: 289,
    overviewTier: 5,
    oss: false,
    freeKind: "byok",
    freeNote: "Pay-per-token (no sub)",
    blurb: "Cheapest open-weights inference. 289 models.",
    url: "https://deepinfra.com",
  },
  {
    id: "together",
    name: "Together AI",
    category: "infra",
    price: 1,
    y: 200,
    overviewTier: 5,
    oss: false,
    freeKind: "byok",
    freeNote: "Pay-per-token (no sub)",
    blurb: "200+ OSS models. Fine-tuning. $0.02–7/M tokens.",
    url: "https://together.ai",
  },
  // Aggregator
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "infra",
    price: 1,
    y: 351,
    overviewTier: 5,
    oss: false,
    freeKind: "yes",
    freeNote: "25+ genuinely free models",
    blurb: "351 models from 60+ providers. Upstream + 5.5% fee.",
    url: "https://openrouter.ai",
  },
  // Pure gateways: BYOK, any model, no catalog
  {
    id: "cf-gateway",
    name: "Cloudflare AI Gateway",
    category: "infra",
    price: 1,
    y: 500,
    overviewTier: 5,
    oss: false,
    freeKind: "yes",
    freeNote: "Free on all CF plans",
    blurb: "Pure gateway. BYOK any provider. Cache + rate limits.",
    url: "https://developers.cloudflare.com/ai-gateway",
  },
  {
    id: "vercel-gateway",
    name: "Vercel AI Gateway",
    category: "infra",
    price: 1,
    y: 500,
    overviewTier: 5,
    oss: false,
    freeKind: "yes",
    freeNote: "$5/mo credits included",
    blurb: "Pure gateway. BYOK any provider. Zero markup on upstream.",
    url: "https://vercel.com/docs/ai-gateway",
  },
];

export const CATEGORY_LABELS: Record<Category, string> = {
  chat: "Chat",
  ide: "IDE",
  cli: "CLI",
  infra: "Infra",
};

export const CATEGORY_DESCRIPTIONS: Record<Category, string> = {
  chat: "Conversational UI. No repo access.",
  ide: "Editor with AI inside. Autocomplete to full agent.",
  cli: "Terminal agent. Operates on your filesystem.",
  infra: "Gateways + providers. All pay-per-token (no subs). X axis is nominal.",
};

export const Y_AXIS_LABELS: Record<Category, string> = {
  chat: "Context window",
  ide: "Autonomy",
  cli: "Scope",
  infra: "Models supported",
};

// Legacy capability labels for the overview chart
export const TIER_LABELS: Record<number, string> = {
  1: "Chat",
  2: "Autocomplete",
  3: "Editor agent",
  4: "Terminal agent",
  5: "API fabric",
};

export const FREE_KIND_LABELS: Record<Tool["freeKind"], string> = {
  yes: "Genuinely free",
  trial: "Free tier (limited)",
  byok: "Free binary, paid API",
  none: "No free tier",
};

// Y-axis specifics per category
export type YAxisConfig = {
  type: "log" | "linear";
  min: number;
  max: number;
  ticks: number[];
  format: (v: number) => string;
};

export const Y_CONFIG: Record<Category, YAxisConfig> = {
  chat: {
    type: "log",
    min: 32,
    max: 1200,
    ticks: [32, 128, 256, 512, 1000],
    format: (v) => (v >= 1000 ? `${v / 1000}M` : `${v}K`),
  },
  ide: {
    type: "linear",
    min: 0.5,
    max: 4.5,
    ticks: [1, 2, 3, 4],
    format: (v) => ["", "complete", "edit", "agent", "auto"][v] ?? "",
  },
  cli: {
    type: "linear",
    min: 0.5,
    max: 4.5,
    ticks: [1, 2, 3, 4],
    format: (v) => ["", "pair", "tools", "plan", "swarm"][v] ?? "",
  },
  infra: {
    type: "log",
    min: 10,
    max: 600,
    ticks: [10, 50, 100, 300, 500],
    format: (v) => `${v}`,
  },
};
